###

POST http://localhost:3000/clientes/1/transacoes
Content-Type: application/json

{
  "valor": 100000,
  "tipo": "c",
  "descricao" : "descrição"
}

### 

GET http://localhost:3000/clientes/1/extrato
